### PR TITLE
[Feature] Supporting CocoaPods

### PR DESCRIPTION
**Pull request by abdelmagied94**

### CODE REVIEW

**Comment by abdelmagied94** [comment]
@joel-perry Please sign up with an account with your email `joel@joelperry.net` on Cocoapods as described in this `Getting started` [section](https://guides.cocoapods.org/making/getting-setup-with-trunk.html#getting-started) to be able to add you as owner to the library

**Comment by joel-perry** [comment]
Thanks for this @abdelmagied94. I did `pod trunk push` on this and it appears you already did, so it tells me you are the owner of the repo. Is there a way to fix this so I can update when my version changes?

**Comment by abdelmagied94** [comment]
@joel-perry I have added you as Owner. You can check this by executing the following command 
```pod trunk info ApolloCombine```

**Comment by joel-perry** [comment]
Excellent! Once again, thanks for the work on this.

**Pull request merged**
