### PR TITLE
Update to Apollo 1.x

### PR DESCRIPTION
**Pull request by AF-cgi**

### CODE REVIEW

**Review by piro49 — APPROVED** [review]

**Comment by joel-perry** [comment]
Hello @AF-cgi and @piro49!
I have not been using Apollo for a while. Is this all that is required to make ApolloCombine compatible with v1.x?
Thanks, Joel

**Comment by AF-cgi** [comment]
@joel-perry Yes, of course.

**Comment by piro49** [comment]
@joel-perry Yes it works fine with the proposed changes in PR of @AF-cgi.
Thank you for the fast reply. :)

**Comment by joel-perry** [comment]
Excellent. Thanks to both of you!

**Comment by joel-perry** [comment]
@sgade Done! I meant to do it and just got slung off task. Thanks!

**Comment by sgade** [comment]
Thank you very much. Appreciate the super fast response!

**Pull request merged**
